import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { QRCodeSVG } from 'qrcode.react'
import { Bell, ChevronDown, CircleHelp, Copy, ExternalLink, LayoutDashboard, LogOut, Menu, MoreHorizontal, Plus, QrCode, Search, Share2, Swords, Trophy, Users, X } from 'lucide-react'
import './styles.css'

type Player = { id: number; name: string; rating: number | null; club: string | null; points: number; wins: number; draws: number; losses: number; trend?: string[] }
type Match = { id: number; white: string; black: string; result?: string }
type Tournament = { id:number; code:string; name:string; city:string | null; event_date:string; rounds:number; system:string; status:string; players:Player[]; matches:Match[] }

function App() {
  const initialCode = new URLSearchParams(window.location.search).get('codigo')
  const [view, setView] = useState<'judge' | 'public'>(() => window.location.search.includes('juiz=1') ? 'judge' : 'public')
  const [menu, setMenu] = useState(false)
  const [modal, setModal] = useState<'new' | 'share' | 'result' | 'player' | null>(null)
  const [selectedMatch, setSelectedMatch] = useState<Match | null>(null)
  const [tournament, setTournament] = useState<Tournament | null>(null)
  const [loading, setLoading] = useState(true)
  const [query, setQuery] = useState('')
  const [publicCode] = useState(initialCode?.toUpperCase() || '')
  const publicUrl = `${window.location.origin}/?codigo=${encodeURIComponent(publicCode)}`
  const judgeUrl = `${publicUrl}&juiz=1`
  const sorted = useMemo(() => (tournament?.players ?? []).filter(p => p.name.toLowerCase().includes(query.toLowerCase())), [query, tournament])
  const loadTournament = async () => { if (!publicCode) return; const response = await fetch(`/api/tournaments/${publicCode}`); if (response.ok) setTournament(await response.json()); setLoading(false) }
  useEffect(() => { if (!publicCode) { setLoading(false); return }; loadTournament(); const timer = window.setInterval(loadTournament, 5000); return () => window.clearInterval(timer) }, [publicCode])
  const saveResult = async (result: string) => {
    if (!selectedMatch) return
    setModal(null)
    const response = await fetch(`/api/matches/${selectedMatch.id}`, { method: 'PUT', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ result }) })
    if (response.ok) setTournament((await response.json()).tournament)
  }
  if (!publicCode) return <Landing onCreate={()=>setModal('new')} modal={modal} close={()=>setModal(null)} onCreated={(item)=>window.location.href=`/?codigo=${item.code}&juiz=1`}/>
  return <div className="app-shell">
    <aside className={menu ? 'sidebar open' : 'sidebar'}>
      <div className="brand"><div className="brand-mark"><Swords size={22}/></div><span>Xeque<span className="accent">Mate</span></span><button className="mobile-close" onClick={()=>setMenu(false)}><X/></button></div>
      <nav><button className="nav-item active"><LayoutDashboard/>Visão geral</button><button className="nav-item"><Trophy/>Torneios <span className="badge">3</span></button><button className="nav-item"><Users/>Jogadores</button></nav>
      <div className="sidebar-bottom"><button className="nav-item"><CircleHelp/>Central de ajuda</button><div className="profile"><div className="avatar">BS</div><div><b>Bruna Santiago</b><small>Árbitra</small></div><MoreHorizontal size={18}/></div></div>
    </aside>
    <main>
      <header><button className="hamburger" onClick={()=>setMenu(true)}><Menu/></button><div className="crumb"><span>Torneios</span><b>/</b><strong>{tournament?.name || 'Carregando'}</strong><ChevronDown size={15}/></div><div className="top-actions"><button className="public-link" onClick={()=>setView(view === 'judge' ? 'public' : 'judge')}><ExternalLink size={16}/>{view === 'judge' ? 'Ver atualização pública' : 'Voltar ao juiz'}</button></div></header>
      {loading ? <div className="page"><p>Carregando torneio…</p></div> : view === 'judge' ? <JudgeView /> : <PublicView />}
    </main>
    <button className="floating-add" onClick={()=>setModal('new')}><Plus size={20}/> Novo torneio</button>
    {modal === 'new' && <NewTournament onClose={()=>setModal(null)} onCreated={(item)=>window.location.href=`/?codigo=${item.code}&juiz=1`}/>} 
    {modal === 'share' && <ShareModal onClose={()=>setModal(null)} publicUrl={publicUrl} judgeUrl={judgeUrl} code={publicCode}/>} 
    {modal === 'player' && tournament && <PlayerModal tournamentId={tournament.id} onClose={()=>setModal(null)} onCreated={setTournament}/>} 
    {modal === 'result' && selectedMatch && <ResultModal match={selectedMatch} onClose={()=>setModal(null)} onSave={saveResult}/>} 
  </div>

  function JudgeView() { if (!tournament) return null; return <div className="page judge-page"><section className="hero"><div><div className="eyebrow"><span/>{tournament.status === 'finished' ? 'FINALIZADO' : 'EM ANDAMENTO'}</div><h1>{tournament.name}</h1><p>{tournament.city || 'Sem cidade'} · {new Date(`${tournament.event_date}T12:00`).toLocaleDateString('pt-BR')}</p></div><div className="hero-actions"><button className="secondary" onClick={()=>setModal('player')}><Users size={17}/>Jogador</button><button className="secondary" onClick={()=>setModal('share')}><Share2 size={17}/>Compartilhar</button><button className="primary" onClick={()=>setModal('new')}><Plus size={18}/>Novo torneio</button></div></section><section className="stats"><Stat icon={<Users/>} label="Jogadores" value={String(tournament.players.length)} hint="cadastrados"/><Stat icon={<Swords/>} label="Rodada atual" value={`3 de ${tournament.rounds}`} hint={`${tournament.matches.length} partidas`}/><Stat icon={<Trophy/>} label="Sistema" value={tournament.system === 'swiss' ? 'Suíço' : 'Todos contra todos'} hint={`${tournament.rounds} rodadas`}/><Stat icon={<Bell/>} label="Concluídas" value={String(tournament.matches.filter(m=>m.result).length)} hint={`de ${tournament.matches.length} partidas`}/></section><section className="grid"><div className="card standings"><div className="card-head"><div><h2>Classificação</h2><p>Calculada pelo banco local</p></div><button className="text-btn" onClick={()=>setModal('player')}>+ jogador</button></div><div className="table-wrap"><table><thead><tr><th>#</th><th>JOGADOR</th><th>PTS</th><th>V</th><th>E</th><th>D</th><th>RATING</th><th/></tr></thead><tbody>{sorted.map((p,i)=><tr key={p.id}><td><span className={i<3?'rank rank-'+i:'rank'}>{i+1}</span></td><td><div className="player"><div className="mini-avatar">{p.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><div><b>{p.name}</b><small>{p.club || 'Sem clube'}</small></div></div></td><td className="points">{p.points.toFixed(1)}</td><td>{p.wins}</td><td>{p.draws}</td><td>{p.losses}</td><td>{p.rating || '—'}</td><td><button className="dots"><MoreHorizontal size={18}/></button></td></tr>)}</tbody></table></div></div><div className="side-column"><div className="card rounds"><div className="card-head"><div><h2>Rodada 3</h2><p>{tournament.matches.length} partidas</p></div></div>{tournament.matches.map(m=><button className="match" key={m.id} onClick={()=>{setSelectedMatch(m);setModal('result')}}><span className="board">{m.id}</span><div><b>{m.white}</b><b>{m.black}</b></div><span className={m.result?'match-result done':'match-result'}>{m.result || '–'}</span></button>)}</div><div className="public-card"><div><span>ACOMPANHAMENTO AO VIVO</span><h3>Compartilhe seu torneio</h3><p>Espectadores acompanham cada alteração.</p><button onClick={()=>setModal('share')}>Gerar link <ExternalLink size={14}/></button></div><div className="qr"><QrCode size={29}/></div></div></div></section></div> }
  function PublicView() { if (!tournament) return null; return <div className="page public-page"><section className="public-hero"><div className="live-pill"><span/> {tournament.status === 'finished' ? 'FINALIZADO' : 'AO VIVO'}</div><h1>{tournament.name}</h1><p>{tournament.city || 'Torneio local'} · {new Date(`${tournament.event_date}T12:00`).toLocaleDateString('pt-BR')}</p><div className="event-info"><span><Swords/> Rodada <b>3 de {tournament.rounds}</b></span><span><Users/> <b>{tournament.players.length}</b> jogadores</span><span><Trophy/> {tournament.system === 'swiss' ? 'Sistema suíço' : 'Todos contra todos'}</span></div></section><section className="public-content"><div className="public-title"><div><h2>Classificação</h2><p>Atualizada automaticamente</p></div><div className="code-box">CÓDIGO <b>{publicCode}</b><button aria-label="Copiar código" onClick={()=>navigator.clipboard?.writeText(publicCode)}><Copy size={15}/></button></div></div><div className="public-table">{tournament.players.map((p,i)=><div className="public-row" key={p.id}><span className="rank">{i+1}</span><div className="mini-avatar">{p.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><div className="public-name"><b>{p.name}</b><small>{p.club || 'Sem clube'} · {p.rating || 'sem rating'}</small></div><strong>{p.points.toFixed(1)}<small> pts</small></strong></div>)}</div></section></div> }
}
function Landing({onCreate,modal,close,onCreated}:{onCreate:()=>void;modal:'new'|'share'|'result'|'player'|null;close:()=>void;onCreated:(item:Tournament)=>void}) { const [code,setCode]=useState(''); return <div className="landing"><div className="landing-brand"><div className="brand-mark"><Swords size={22}/></div>Xeque<span>Mate</span></div><section><div className="landing-kicker">GESTÃO DE TORNEIOS DE XADREZ</div><h1>Seu campeonato,<br/><em>em movimento.</em></h1><p>Crie o torneio, informe os participantes e tenha a primeira rodada pronta em segundos.</p><button className="primary landing-cta" onClick={onCreate}><Plus size={19}/>Criar campeonato</button><div className="open-code"><span>Já possui um código?</span><form onSubmit={e=>{e.preventDefault(); if(code.trim()) window.location.href=`/?codigo=${encodeURIComponent(code.trim().toUpperCase())}`}}><input value={code} onChange={e=>setCode(e.target.value)} placeholder="Ex.: XAD842"/><button>Ver atualização</button></form></div></section><div className="landing-board"><div>♜</div><div>♞</div><div>♝</div><div>♛</div><div>♚</div><div>♟</div></div>{modal==='new' && <NewTournament onClose={close} onCreated={onCreated}/>}</div> }
function Stat({icon,label,value,hint}:{icon:React.ReactNode,label:string,value:string,hint:string}) { return <div className="stat"><div className="stat-icon">{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{hint}</small></div></div> }
function NewTournament({onClose,onCreated}:{onClose:()=>void;onCreated:(item:Tournament)=>void}) {
  const [saving,setSaving]=useState(false), [error,setError]=useState('')
  const create = async (form:HTMLFormElement) => {
    setSaving(true); setError('')
    const fields = new FormData(form)
    const players = String(fields.get('participants') || '').split('\n').map(line => line.trim()).filter(Boolean).map(line => {
      const [name, rating, club, category] = line.split(';').map(item => item.trim())
      return { name, rating: rating ? Number(rating) : null, club, category }
    }).filter(player => player.name)
    const response = await fetch('/api/tournaments',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:fields.get('name'),players})})
    if(response.ok) onCreated(await response.json()); else { const body = await response.json(); setError(body.error || 'Não foi possível criar o torneio.'); setSaving(false) }
  }
  return <div className="overlay"><form className="modal tournament-modal" onSubmit={e=>{e.preventDefault();create(e.currentTarget)}}><button type="button" className="modal-close" onClick={onClose}><X/></button><div className="modal-icon"><Trophy/></div><h2>Novo campeonato</h2><p>Informe o nome e os participantes. A primeira rodada será gerada automaticamente.</p><label>Nome do campeonato<input name="name" placeholder="Ex.: Campeonato Municipal" required autoFocus/></label><label>Participantes<textarea name="participants" rows={9} required placeholder={'Ana Silva\nBruno Costa\nCarlos Lima\nDaniel Souza'} /></label><small className="form-hint">Um nome por linha. Mínimo de 2 participantes e quantidade par.</small>{error && <p className="form-error">{error}</p>}<button className="primary wide" disabled={saving}>{saving?'Criando…':'Criar campeonato'}</button></form></div>
}
function PlayerModal({tournamentId,onClose,onCreated}:{tournamentId:number;onClose:()=>void;onCreated:(item:Tournament)=>void}) { const [saving,setSaving]=useState(false); const create = async (form:HTMLFormElement) => { setSaving(true); const fields = new FormData(form); const response = await fetch('/api/players',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({tournament_id:tournamentId,name:fields.get('name'),rating:fields.get('rating'),club:fields.get('club'),category:fields.get('category')})}); if(response.ok){ onCreated(await response.json()); onClose() } else setSaving(false) }; return <div className="overlay"><form className="modal" onSubmit={e=>{e.preventDefault();create(e.currentTarget)}}><button type="button" className="modal-close" onClick={onClose}><X/></button><div className="modal-icon"><Users/></div><h2>Adicionar jogador</h2><p>O jogador será salvo no torneio atual.</p><label>Nome completo<input name="name" required autoFocus placeholder="Nome do jogador"/></label><div className="fields"><label>Rating FIDE<input name="rating" type="number" min="0" placeholder="Opcional"/></label><label>Clube ou cidade<input name="club" placeholder="Opcional"/></label></div><label>Categoria<input name="category" placeholder="Ex.: Sub-18"/></label><button className="primary wide" disabled={saving}>{saving?'Salvando…':'Adicionar jogador'}</button></form></div> }
function ShareModal({onClose, publicUrl, judgeUrl, code}:{onClose:()=>void;publicUrl:string;judgeUrl:string;code:string}) { return <div className="overlay"><div className="modal share-modal"><button className="modal-close" onClick={onClose}><X/></button><div className="modal-icon"><Share2/></div><h2>Links do campeonato</h2><p>Envie a atualização ao público e mantenha o link do juiz em privado.</p><div className="share-code">{code}</div><label className="share-label">LINK PÚBLICO — ATUALIZAÇÃO</label><div className="share-link"><span>{publicUrl}</span><button aria-label="Copiar link público" onClick={()=>navigator.clipboard?.writeText(publicUrl)}><Copy size={16}/></button></div><label className="share-label">LINK DO JUIZ — LANÇAR PONTUAÇÃO</label><div className="share-link"><span>{judgeUrl}</span><button aria-label="Copiar link do juiz" onClick={()=>navigator.clipboard?.writeText(judgeUrl)}><Copy size={16}/></button></div><div className="qr-large"><QRCodeSVG value={publicUrl} size={140}/></div><button className="primary wide" onClick={onClose}>Concluído</button></div></div> }
function ResultModal({match,onClose,onSave}:{match:Match;onClose:()=>void;onSave:(x:string)=>void}) { const [result,setResult]=useState(match.result || ''); return <div className="overlay"><div className="modal result-modal"><button className="modal-close" onClick={onClose}><X/></button><h2>Registrar resultado</h2><p>Tabuleiro {match.id} · Rodada 3</p><div className="versus"><b>{match.white}</b><span>×</span><b>{match.black}</b></div><div className="result-options">{[['1–0','Vitória das brancas'],['½–½','Empate'],['0–1','Vitória das pretas'],['WO','Walkover']].map(([v,l])=><button className={result===v?'chosen':''} onClick={()=>setResult(v)} key={v}><b>{v}</b><small>{l}</small></button>)}</div><button className="primary wide" disabled={!result} onClick={()=>onSave(result)}>Salvar resultado</button></div></div> }

createRoot(document.getElementById('root')!).render(<App />)
